server:
    port: 9000
    contextPath:

spring:
    profiles:
        active: production

    thymeleaf:
        cache: true

    jade4j:
        caching: true

    redis:
      host: localhost
      port: 6379
      default_expire_time: 86400

