server:
    port: 9000
    contextPath:

spring:
    profiles:
        active: dev

    thymeleaf:
        cache: false

    jade4j:
        caching: false

    redis:
      host: localhost
      port: 6379
      default_expire_time: 86400

